volumes:
  caddy_data:
services:
  fbi-proxy:
    build: .
    image: snomiao/fbi-proxy
    volumes:
      - ./services.yaml:/fbi/services.yaml
      - caddy_data:/etc/caddy/data
    network_mode: host
